services:
  debian_psql:
    image: debian:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: my-postgres
      PG_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - my-network

  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_password

networks:
  my-network:

secrets:
  db_password:
    file: ./db_password.txt